swagger: '2.0'
info:
  title: STRATUS service
  description: Analytic Services Integration Framework
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
basePath: /hpda
paths:
    /user_ids:
      get:
        operationId: stratus.handlers.hpda.getUserIds
        description: Returns a list of ids
        produces:
        - application/json
        responses:
          '200':
            description: List of Ids
            schema:
                type: array
                items:
                    type: integer
