swagger: '2.0'
info:
  title: STRATUS service
  description: Analytic Services Integration Framework
  contact:
    name: Thomas Maxwell
    email: thomas.maxwell@nasa.gov
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
basePath: /hpda
paths:
    /user_ids:
      get:
        operationId: stratus.handlers.hpda.getUserIds
        description: Returns a list of ids
        produces:
        - application/json
        responses:
          '200':
            description: List of Ids
            schema:
                type: array
                items:
                    type: integer
    /exe:
      get:
        operationId: stratus.handlers.hpda.exe
        description: Executes an analytics request
      parameters:
      - name: id
        in: path
        description: ID of pet to use
        required: true
        schema:
          type: array
          style: simple
          items:
            type: object
#        parameters:
#          - name: variables
#            description: List of input variables
#            in: query
#            required: true
#            schema:
#              type: array
#              items:
#                type: string
#          - name: domains
#            description: List of domains
#            in: query
#            required: false
#            schema:
#              type: array
#              items:
#                type: string
#          - name: operations
#            description: List of analytic operations
#            in: query
#            required: false
#            schema:
#              type: array
#              items:
#                type: string
#      produces:
#      - application/json
      responses:
        '200':
          description: a response to be returned
          content:
            application/json:
              schema:
                type: array
                style: simple
                items:
                  type: object