swagger: "2.0"
info:
  title: STRATUS service
  description: Analytic Services Integration Framework
  contact:
    name: Thomas Maxwell
    email: thomas.maxwell@nasa.gov
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
basePath: /hpda
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /exe:
    get:
      operationId: stratus.handlers.hpda.exe
      description: Executes an analytics request
      parameters:
        - name: variables
          in: query
          description: List of input variables
          required: true
          type: array
          items:
            type: string
        - name: domains
          in: query
          description: List of domains
          required: false
          type: array
          items:
            type: string
        - name: operations
          in: query
          description: Workflow composed of analytic operations
          required: false
          type: array
          items:
            type: string
      responses:
        "200":
          description: Result of analytic operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Result'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: stratus.handlers.hpda.testOp1
      parameters:
        - name: pet
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/NewResult'
      responses:
        "200":
          description: pet response
          schema:
            $ref: '#/definitions/Result'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /pets/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: stratus.handlers.hpda.testOp2
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        "200":
          description: pet response
          schema:
            $ref: '#/definitions/Result'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: stratus.handlers.hpda.testOp3
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          type: integer
          format: int64
      responses:
        "204":
          description: pet deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Result:
    allOf:
      - $ref: '#/definitions/NewResult'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64

  NewResult:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string

  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string